# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-15 06:00
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_recruitment_recruitmentform'),
    ]

    operations = [
        migrations.CreateModel(
            name='Creatia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cretia_name', models.CharField(max_length=200)),
                ('point', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
            ],
        ),
        migrations.CreateModel(
            name='Questionnaire',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_name', models.CharField(max_length=200)),
                ('answer', models.CharField(max_length=200)),
                ('recruitment_form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.RecruitmentForm')),
            ],
        ),
        migrations.CreateModel(
            name='Round',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round_num', models.IntegerField()),
                ('round_name', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='questionnaire',
            name='round',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Round'),
        ),
        migrations.AddField(
            model_name='creatia',
            name='questionnaire',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Questionnaire'),
        ),
        migrations.AddField(
            model_name='creatia',
            name='round',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Round'),
        ),
    ]
