# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-16 03:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0006_recruitmentform_year_program'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recruitmentform',
            name='year_program',
            field=models.IntegerField(max_length=200),
        ),
    ]
