# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-16 03:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0007_auto_20170616_1017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recruitmentform',
            name='year_program',
            field=models.IntegerField(),
        ),
    ]
