# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-16 05:11
from __future__ import unicode_literals

from django.db import migrations, models
import froala_editor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0008_auto_20170616_1018'),
    ]

    operations = [
        migrations.AddField(
            model_name='recruitment',
            name='content',
            field=froala_editor.fields.FroalaField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='recruitment',
            name='description',
            field=models.TextField(),
        ),
    ]
