# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-24 14:12
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import froala_editor.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('polls', '0009_auto_20170616_1211'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=200)),
                ('project_description', models.TextField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='ProjectOfKind',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_kind', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='PublishedEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=200)),
                ('event_description', froala_editor.fields.FroalaField()),
                ('create_date', models.DateTimeField(verbose_name=b'Created Date')),
                ('pub_date', models.DateTimeField(verbose_name=b'Publised Date')),
                ('closed_date', models.DateTimeField(verbose_name=b'Closed Date')),
            ],
        ),
        migrations.CreateModel(
            name='RegisterEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=200)),
                ('customer_phone', models.IntegerField()),
                ('customer_email', models.EmailField(max_length=200)),
                ('question', models.CharField(max_length=500)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.PublishedEvent')),
            ],
        ),
        migrations.CreateModel(
            name='SubProject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subproject_name', models.CharField(max_length=200)),
                ('subproject_description', models.TextField(max_length=1000)),
                ('create_date', models.DateTimeField(verbose_name=b'Created Date')),
                ('closed_date', models.DateTimeField(verbose_name=b'Closed Date')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Project')),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_name', models.CharField(max_length=200)),
                ('requirement', models.TextField(max_length=1000)),
                ('submit_file', models.FileField(upload_to=b'profile_image')),
                ('commemt', models.TextField(blank=True, max_length=1000)),
                ('due_date', models.DateTimeField(verbose_name=b'Due Date')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.SubProject')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='publishedevent',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.SubProject'),
        ),
        migrations.AddField(
            model_name='project',
            name='project_kind',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.ProjectOfKind'),
        ),
    ]
