# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-24 17:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0010_auto_20170624_2112'),
    ]

    operations = [
        migrations.CreateModel(
            name='LocalCommittee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('local_committee', models.CharField(default=b'HN', max_length=200)),
                ('City', models.CharField(default=b'Hanoi', max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='project',
            name='local_committee',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='polls.LocalCommittee'),
            preserve_default=False,
        ),
    ]
