# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-24 17:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0011_auto_20170625_0031'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='local_committee',
        ),
    ]
