# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-24 17:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0012_remove_project_local_committee'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='local_committee',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='polls.LocalCommittee'),
            preserve_default=False,
        ),
    ]
